### ISSUE TITLE
found another project similar to yours

### ISSUE THREAD

**Issue by gbstack** [shanta3220/Riko-The-Adventurer#1]
Hi,
this game you developed is great!
But I found a very similar game similar to yours (even the source code is almost same).
https://github.com/SouthBegonia/DeathtrapDungeon

Is that project also developed by you?

**Comment by shanta3220** [comment]
Thank you.

No, it's not mine. But when I worked on the project I followed this following Tutorial initially to create the base, so code could be same if that developer followed.

https://www.udemy.com/course/learn-unity-engine-by-making-a-top-down-rpg/
